export const HTTP_STATUS = {
  SUCCESS: 200,
  CREATED: 201,
  ACCEPTED: 202,
  CLIENT_ERROR: 400,
  AUTHENTICATE: 301,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504
};
export const cache = {
  loginInfo: 'userInfo'
};

export const REFRESH_STATUS = {
  NORMAL: 0,
  REFRESHING: 1,
  NO_MORE_DATA: 2
};

// 首页
// 推荐列表
export const ACTION_SET_RECOMMEND_LIST = 'ACTION_SET_RECOMMEND_LIST';
// 推荐电台
export const ACTION_SET_DJ_LIST = 'ACTION_SET_DJ_LIST';
// banner
export const ACTION_SET_BANNER_LIST = 'ACTION_SET_BANNER_LIST';
// 我的页面 缓存用户信息
export const ACTION_SET_USER_INFO = 'ACTION_SET_USER_INFO';
// 退出登录
export const ACTION_SET_LOUGOUT = 'ACTION_SET_LOUGOUT';
